routes/web.php
<?php

use Illuminate\Support\Facades\Input;

/*******************************************************************************************
 *                                  AUTH
 *******************************************************************************************/

Auth::routes();

/*******************************************************************************************
 *                                  BACKEND
 *******************************************************************************************/

Route::group(['prefix' => 'backend', 'middleware' => 'backend', 'namespace' => 'Backend'], function () {
    // Dashboard
    Route::get('/', ['uses' => 'BackendsController@index', 'as' => 'backend.index']);

    // Posts
    Route::group(['prefix' => 'posts'], function () {
        Route::get('/trashed', ['uses' => 'PostsController@trashed', 'as' => 'posts.trashed']);
        Route::get('/shred/{id}', ['uses' => 'PostsController@shred', 'as' => 'posts.shred']);
        Route::delete('/massdelete', ['uses' => 'PostsController@massdelete', 'as' => 'posts.massdelete']);
        Route::get('/all', ['uses' => 'PostsController@allposts', 'as' => 'posts.all']);
    });

    Route::resource('posts', 'PostsController', ['except' => ['show', 'destroy']]);

    // Users
    Route::group(['prefix' => 'users'], function () {
        Route::get('/myaccount', ['uses' => 'UsersController@myaccount', 'as' => 'users.myaccount']);
        Route::post('/profile/update', ['uses' => 'ProfilesController@update', 'as' => 'profile.update']);
        Route::delete('/massdelete', ['uses' => 'UsersController@massdelete', 'as' => 'users.massdelete']);
    });
    Route::resource('users', 'UsersController');

    // Roles
    Route::group(['prefix' => 'roles'], function () {
        Route::delete('/massdelete', ['uses' => 'RolesController@massdelete', 'as' => 'roles.massdelete']);
    });
    Route::resource('roles', 'RolesController');

    // Permissions
    Route::group(['prefix' => 'permissions'], function () {
        Route::delete('/massdelete', ['uses' => 'PermissionsController@massdelete', 'as' => 'permissions.massdelete']);
    });
    Route::resource('permissions', 'PermissionsController');

    // Models
    Route::group(['prefix' => 'models'], function () {
        Route::delete('/massdelete', ['uses' => 'DatasetsController@massdelete', 'as' => 'models.massdelete']);

    });
    Route::resource('models', 'DatasetsController');

    // Menu Management Page
    Route::get('/menu', function () {
        $menu = DB::table('tbl_menus')->orderBy('order', 'ASC')->get();
        return view('backend.menus.menu', ['menus' => $menu]);
    });

    // Menu Manager
    Route::get('/managemenu', function () {
        $menu = DB::table('tbl_menus')->orderBy('order', 'ASC')->get();
        return view('backend.menus.menuManage', ['menus' => $menu]);
    });

    // Menu Sorter Function
    Route::get('/order-menu', function () {
        $menu = DB::table('tbl_menus')->orderBy('order', 'ASC')->get();
        $itemID = Input::get('itemID');
        $itemIndex = Input::get('itemIndex');

        foreach ($menu as $value) {
            return DB::table('tbl_menus')
                ->where('menu_id', '=', $itemID)
                ->update(array('order' => $itemIndex));
        }
        return redirect()->route('backend.index');
    });

    // Comments
    Route::group(['prefix' => 'comments'], function () {
        Route::delete('/massdelete', ['uses' => 'CommentsController@massdelete', 'as' => 'comments.massdelete']);
    });
    Route::resource('comments', 'CommentsController', ['except' => ['show', 'store', 'destroy']]);

    // Email

    Route::post('/send/email', ['uses'=> 'EmailController@send', 'as'=> 'emails.send']);
});

Route::get('/', ['uses' => 'HomeController@index']);

app/Models/Backend/Comment.php
<?php

namespace App\Models\Backend;
use App\Models\Backend\Post;
use App\Models\Backend\Category;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $guarded = [];
    
    public function post()
    {
        return $this->belongsTo(Post::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    
    public function category(){
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/Backend/BackendsController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

class BackendsController extends Controller
{
    public function index(){
        // return view('backend.dashboard');
        return redirect()->route('posts.all');
    }
}

app/Http/Controllers/Backend/CommentsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Backend\Comment;
use App\Models\Backend\Post;
use Illuminate\Http\Request;
use Session;
use App\Http\Requests\Backend\CommentsRequest;

class CommentsController extends Controller
{
    public function index(){
        return view('backend.comments.index')
        ->with('comments', Comment::all());
    }

    public function save(CommentsRequest $request,Post $post)
    {        
        $post->saveComment(
            request('description')
        );
        
        Session::flash('success', 'Your comment has been posted successfully');
        return redirect()->back();
    }

    public function edit($id){
        return view('backend.comments.edit')
        ->with('comment', Comment::find($id));        
    }

    public function update(CommentsRequest $request, $id){
        
        Comment::find($id)->update([
            'description' => $request->description,            
        ]);
        Session::flash('success', 'The comment was successfully updated');
        return redirect()->back();
    }

    public function massdelete(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Comment::find($id)->delete();
        }
        Session::flash('success', 'The comment(s) was successfully deleted');
        return redirect()->route('comments.index');
    }  
    
    public function kill(Post $post){
        $post->deleteComment(request('id'));
        Session::flash('success', 'The comment(s) was successfully deleted');
        return redirect()->route('comments.index');
    }
}

app/Http/Controllers/Backend/DatasetsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Backend\Dataset;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\DatasetsRequest;
use Illuminate\Http\Request;
use Session;

class DatasetsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.models.index')->with('datasets', Dataset::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.models.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DatasetsRequest $request)
    {
        Dataset::create([
            'name' => $request->name,
            'key' => str_slug($request->name),
            'description' => $request->description,
        ]);
        Session::flash('success', 'The model has been created');
        return redirect()->route('models.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('backend.models.edit')->with('dataset', Dataset::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DatasetsRequest $request, $id)
    {
        Dataset::find($id)->update([
            'name' => $request->name,
            'key' => str_slug($request->name),
            'description' => $request->description,
        ]);
        Session::flash('success', 'The model has been updated');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }

    public function massdelete(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Dataset::find($id)->delete();
        }
        Session::flash('success', 'The dataset(s) was successfully deleted');
        return redirect()->route('models.index');
    }
}

app/Http/Controllers/Backend/EmailController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EmailController extends Controller
{
    public function send(Request $request){
        
    }
}

app/Http/Controllers/Backend/PermissionsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Backend\Dataset;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\PermissionsRequest;
use App\Models\Permission;
use Illuminate\Http\Request;
use Session;

class PermissionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.permissions.index')->with('permissions', Permission::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.permissions.create')->with('models', Dataset::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PermissionsRequest $request)
    {
        Permission::create([
            'name' => ucwords($request->name),
            'slug' => str_slug($request->name),
            'description' => $request->description,
            'dataset_id' => $request->dataset_id
        ]);
        Session::flash('success', 'The permission was created successfully');
        return redirect()->route('permissions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('backend.permissions.edit')
        ->with('permission', Permission::find($id))
        ->with('models', Dataset::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PermissionsRequest $request, $id)
    {
        Permission::find($id)->update([
            'name' => ucwords($request->name),
            'slug' => str_slug($request->name),
            'description' => $request->description,
            'dataset_id' => $request->dataset_id
        ]);
        Session::flash('success', 'The permission has been updated successfully');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function massdelete(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Permission::find($id)->delete();
        }
        Session::flash('success', 'The permission(s) was successfully deleted');
        return redirect()->route('permissions.index');
    }
}

app/Http/Controllers/Backend/PostsController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\PostsRequest;
use DB;
use Auth;
use App\Models\Backend\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Session;
use Carbon\Carbon;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.posts.index')
        ->with('posts', Post::all());
    }

    public function allposts(){
        return view('backend.posts.all')
        ->with('posts', Post::all());
    }

    public function singlePost($post_slug){
        $post = Post::where('post_slug', $post_slug)->first();
        return view('backend.posts.single')->with('post', $post);
    }
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        return view('backend.posts.create');        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostsRequest $request)
    {
        
        $this->validate($request, [
            'post_featuredimg' => 'image',
        ]);
        // Start saving the image to /public/uploads/posts
        $featured = $request->file('post_featuredimg');
        $featured_new_name = time() . $featured->getClientOriginalName();
        $featured->move('uploads/post/', $featured_new_name);
        // Create new post
        $post = Post::create([
            'post_title' => $request->post_title,
            'post_slug' => str_slug($request->post_title),
            'post_content' => $request->post_content,
            'post_featuredimg' => '/uploads/post/' . $featured_new_name,
            'user_id' => Auth::id()
        ]);       

        // $post->post_categories()->attach($request->postcats);
        Session::flash('success', 'The post was succesfully saved');
        return redirect()->route('posts.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {               
        $post = Post::find($id);        
        return view('backend.posts.edit')
            ->with('post', $post);            
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostsRequest $request, $id)
    {
            $post = Post::find($id);
            $post->post_title = $request->post_title;
            $post->post_slug = str_slug($request->post_title);
            $post->post_content = $request->post_content;            
        
        if ($request->hasFile('post_featuredimg')) {
            $this->validate($request, [
                'featured' => 'image',
            ]);
            $featured = $request->file('post_featuredimg');
            $featured_new_name = time() . $featured->getClientOriginalName();
            $featured->move('uploads/posts', $featured_new_name);
            $post->post_featuredimg = '/uploads/posts/'.$featured_new_name;            
        }
            $post->save();
        Session::flash('success', 'The post was successfully update');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function massdelete(Request $request)
    {   
        $checked = $request->input('id', []);
        foreach($checked as $id){
            Post::find($id)->delete();
        }        
        Session::flash('success', 'The post was successfully deleted');
        return redirect()->route('posts.index');
    }  

    

    /**
     * Display a listing of the trashed posts.
     *
     * @return \Illuminate\Http\Response
     */

    public function trashed()
    {
        $posts = Post::onlyTrashed()->get();
        return view('backend.posts.trashed')->with('posts', $posts);

    }

    public function shred(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Post::onlyTrashed()->where('id', $id)->forceDelete();
        }
        Session::flash('success', 'The post was successfully deleted');
        return redirect()->route('posts.trashed');

    }

    public function bulkdelete(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Post::where('id', $id)->delete();
        }
        Session::flash('success', 'The post was successfully deleted');
        return redirect()->back();

    }

    public function restore(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Post::onlyTrashed()->where('id', $id)->restore();
        }
        Session::flash('success', 'The post was successfully restored');
        return redirect()->back();

    }
}

resources/views/backend/posts/all.blade.php
@extends('backend.master') @section('content')

<div class="element-wrapper">
<h6 class="element-header">
				All Posts
            </h6>
<div class="row">              
            @foreach($posts as $post)
            <div class="col-md-4 col-sm-12 col-lg-4 mt-2">
                <div class="card" style="">
                    <img class="card-img-top" data-src="" alt="100%x180" style="height: 180px; width: 100%; display: block;" src="{{$post['post_featuredimg']}}"
                        data-holder-rendered="true">
                    <div class="card-body">
                        <h5 class="card-title">{{str_limit($post['post_title'],$limit=44,$end='...')}}</h5>
                        <p class="card-text">{!! str_limit($post['post_content'], $limit = 150, $end = '...') !!}</p>
                        <a href="{{$post['post_slug']}}" class="btn btn-primary">Read More...</a>
                    </div>
                </div>
            </div>

            @endforeach
    
</div>
</div>
@endsection

resources/views/backend/posts/create.blade.php
@extends('backend.master') 
@section('content')
<div class="row">
	<div class="col-lg-12">
		<div class="element-wrapper">
			<h6 class="element-header">
				Create New Post
			</h6>
			<form action="{{route('posts.store')}}" method="POST" enctype="multipart/form-data">
			<div class="element-box">										
						<button class="btn btn-primary" type="submit" name="saveback"> Save Post</button>
                        <a class="btn btn-info" href="{{route('posts.index')}}"> Cancel</a>				
			</div>
			<div class="element-box">				
					{{csrf_field()}}
                    @include('backend.posts.form')									
			</div>
			</form>
		</div>
	</div>
</div>
@stop


@section('ckeditor-js')
 <script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js"></script>
<script>
ClassicEditor
    .create( document.querySelector( '#content' ) )
    .then( editor => {
        console.log( editor );
    } )
    .catch( error => {
        console.error( error );
    } );
</script>
@stop

resources/views/backend/posts/edit.blade.php
@extends('backend.master')
@section('content')
<div class="row">
	<div class="col-lg-12">
		<div class="element-wrapper">
			<h6 class="element-header">
				Edit Post: {{$post->title}}
			</h6>
				<form action="{{route('posts.update',['id'=>$post->id])}}" method="post" enctype="multipart/form-data">
				<div class="element-box">
						<button class="btn btn-primary" type="submit"> Save Changes</button>
                          <a class="btn btn-info" href="{{route('posts.index')}}"> Back</a>
			</div>
				<div class="element-box">
					{{csrf_field()}}
                    {{ method_field('PUT') }}
                    @include('backend.posts.form')
</div>
				</form>

		</div>
	</div>
</div>
@stop


@section('ckeditor-js')
 <script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js"></script>
<script>
ClassicEditor
    .create( document.querySelector( '#content' ) )
    .then( editor => {
        console.log( editor );
    } )
    .catch( error => {
        console.error( error );
    } );
</script>
@stop

resources/views/backend/posts/form.blade.php
					<div class="row">
						<div class="col-md-6">
						<div class="form-group{{ $errors->has('post_title') ? ' has-error' : '' }}">
						<label for=""> Title</label>
						<input name="post_title" type="text" class="form-control" value="{{old('post_title',$post->post_title ?? null)}}">
            @if ($errors->has('post_title'))
						<span class="help-block text-danger">
							<strong>{{ $errors->first('post_title') }}</strong>
						</span>
						@endif
					</div>										
					<div class="form-group{{ $errors->has('post_content') ? ' has-error' : '' }}">
						<label for="">
							Content
						</label>
						<textarea class="form-control" name="post_content" id="content" cols="30" rows="10">{{old('post_content',$post->post_content ?? null)}}</textarea>
            @if ($errors->has('post_content'))
						<span class="help-block text-danger">
							<strong>{{ $errors->first('post_content') }}</strong>
						</span>
						@endif
					</div>
						</div>
						<div class="col-md-6">
							<div class="form-group{{ $errors->has('post_featuredimg') ? ' has-error' : '' }}">
						<label for=""> Featured Image</label>
						<br>
						<input name="post_featuredimg" type="file" class="">
						@if(!empty($post->post_featuredimg))
						<img class="img-responsive img-thumbnail mx-auto d-block" src="{{$post->post_featuredimg}}">
						<p class="badge badge-info mt-2">File path: {{$post->post_featuredimg}}</p>
						@else
						<img src="" alt="" src="{{asset('img/photo.svg')}}">
						@endif												
            @if ($errors->has('post_featuredimg'))
						<span class="help-block text-danger">
							<strong>{{ $errors->first('post_featuredimg') }}</strong>
						</span>
						@endif
					</div>
						</div>
					</div>

resources/views/backend/posts/index.blade.php
@extends('backend.master')
@section('content')
@if($posts->count() >0)
<div class="row">
	<div class="col-sm-12">
		<div class="element-wrapper">
			<h6 class="element-header">
				All Posts
			</h6>
			<form class="form" action="{{route('posts.massdelete')}}" method="post">
			{{csrf_field()}}
			{{method_field('DELETE')}}
			<div class="element-box">
			<div class="element-box-content">
			<div class="btn-group">
				<a href="{{route('posts.create')}}" class="btn btn-primary">Add New Post</a>
			</div>
			<div class="btn-group">
				<button  class="btn btn-danger" id="bulk-delete" type="submit" name="bulkdelete" value="bulkdelete"  onclick="return confirm('Are you sure you want to move the selected record(s) to trash?')"><i class="os-icon os-icon-ui-15"></i> Move To Trash</button>
			</div>
			</div>
			</div>
			<div class="element-box">

				<div class="table-responsive">
					<table id="datatable" class="table table-striped ">
						<thead>
							<tr>
								<th><input type="checkbox" id="selectall" class="checked" {{$posts->count() > 0 ? '':'disabled'}} /></th>														
								<th>#</th>
								<th>Post Title</th>								
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							@foreach($posts as $key=>$post)
							<tr>
								<td><input type="checkbox" name="id[]"
								value="{{$post->id}}" class="check-all"></td>
								<td>{{++$key}}</td>								
								<td>{{$post->post_title}}</td>								
								<td class="row-actions">
									<a href="{{route('posts.edit',['id'=>$post->id])}}">
										<i class="os-icon os-icon-pencil-2"></i> Edit
									</a>														
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
			</form>
		</div>
	</div>
</div>
@else
	<div class="text-center">
<img src="{{asset('img/create.svg')}}" alt="" width="300px" style="padding: 20px 0"/>
<h4>There is no Post. <a href="{{route('posts.create')}}">Click here to add.</a></h4>
</div>
@endif
@endsection

@include('backend.asset-partials.datatables')
@include('backend.asset-partials.form-function')

resources/views/backend/posts/show.blade.php
@extends('backend.master')
@section('content')
@if($posts->count() >1)
<div class="row">
	<div class="col-sm-12">
		<div class="element-wrapper">
			<h6 class="element-header">
				All Posts
			</h6>
			<form class="form" action="{{route('posts.massdelete')}}" method="post">
			{{csrf_field()}}
			{{method_field('DELETE')}}
			<div class="element-box">
			<div class="element-box-content">
			<div class="btn-group">
				<a href="{{route('posts.create')}}" class="btn btn-primary">Add New Post</a>
			</div>
			<div class="btn-group">
				<button  class="btn btn-danger" id="bulk-delete" type="submit" name="bulkdelete" value="bulkdelete"  onclick="return confirm('Are you sure you want to move the selected record(s) to trash?')"><i class="os-icon os-icon-ui-15"></i> Move To Trash</button>
			</div>
			</div>
			</div>
			<div class="element-box">

				<div class="table-responsive">
					<table id="datatable" class="table table-striped ">
						<thead>
							<tr>
								<th><input type="checkbox" id="selectall" class="checked" {{$posts->count() > 0 ? '':'disabled'}} /></th>
								<th>#</th>
								<th>Featured Image</th>
								<th>Post Name</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							@foreach($posts as $key=>$post)
							<tr>
								<td><input type="checkbox" name="id[]"
								value="{{$post->id}}" class="check-all"></td>
								<td>{{++$key}}</td>
								<td>
									<img src="{{$post->post_featuredimg}}" class="img-responsive" width="100px" />
								</td>
								<td>{{$post->post_title}}</td>
								<td class="row-actions">
									<a href="{{route('posts.edit',['id'=>$post->id])}}">
										<i class="os-icon os-icon-pencil-2"></i> Edit
									</a>														
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
			</form>
		</div>
	</div>
</div>
@else
	<div class="text-center">
<img src="{{asset('img/create.svg')}}" alt="" width="300px" style="padding: 20px 0"/>
<h4>There is no Post. Click here to add.</h4>
</div>
@endif
@endsection

@include('backend.asset-partials.datatables')
@include('backend.asset-partials.form-function')

resources/views/backend/posts/single.blade.php
{{--  @extends('backend.master') @section('content')
<div class="row">
    <div class="col-md-6 offset-md-3">
        <img class="img-fluid rounded" src="{{asset($post->post_featuredimg)}}" alt="">
        <h3 class="mt-3">{{$post->post_title}}</h3>
        <p class="content text-justify">
            {!! $post->post_content !!}
        </p>
        <p>
            <b>Posted by</b> {{$post->user->name}} | {{$post->created_at->toDayDateTimeString()}}</p>
        <hr>
        <form method="POST" action="{{route('comments.save', ['id'=> $post->id] )}}">
            {{ csrf_field() }}
            <div class="media">
                <img class="mr-3" src="{{asset(Auth::user()->profile->avatar)}}" width="50px">
                <div class="media-body">
                    <h5 class="mt-0">{{Auth::user()->name}}</h5>
                    <div class="form-group">
                        <textarea name="description" placeholder="Say something?" class="form-control" required></textarea>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Add comment</button>
                    </div>
                </div>
            </div>
        </form>
        <hr> @foreach($post->comments as $comment)
        <div class="media">
            <img class="mr-3" src="{{asset($comment->user->profile->avatar)}}" width="70px">
            <div class="media-body">
                <h5 class="mt-0">{{$comment->user->name}}
                    <small>
                        <i>
                            <b>posted on</b> {{ $comment->created_at->toDayDateTimeString()}}</i>
                    </small>
                </h5>
                <div class="comment-editable">
                <div class="comment-description">
                    {!! $comment->description !!}
                </div>
                <br> 
                @if($comment->user->id == Auth::id())
                
                <form method="POST" href="{{route('comments.kill', ['id'=>$comment->id])}}">
                    {{csrf_field()}}
                    {{method_field('DELETE')}}
                <input type="submit" class="btn btn-link" value="Edit">   
                <input type="submit" class="btn btn-link" value="Delete" />                        
                </form>  
                @endif
            </div>
        </div>
    </div>
    <br> @endforeach
</div>
</div>

@endsection
  --}}

resources/views/backend/posts/trashed.blade.php
@extends('backend.master')
@section('content')
<div class="row">
	<div class="col-sm-12">
		<div class="element-wrapper">
			<h6 class="element-header">
				Trashed Posts
			</h6>
			<form action="" method="post">
			{{csrf_field()}}
			<div class="element-box sticky-top">
			<div class="element-box-content">				
				<div class="btn-group">
				<button  class="btn btn-success" id="restore" type="submit" name="restore" value="restore"><i class="os-icon os-icon-common-07"></i> Restore</button>
				</div>
				<div class="btn-group">
				<button  class="btn btn-danger" id="bulk-delete" type="submit" name="shred" value="shred"  onclick="return confirm('Are you sure you want to permanently delete the record(s)?')"><i class="os-icon os-icon-ui-15"></i> Permanently Delete</button>
					</div>
			</div>
			</div>
			<div class="element-box">
				<div class="table-responsive">
					<table id="datatable" class="table table-striped ">
						<thead>
							<tr>
							<th>
							
							<input type="checkbox" id="selectall" class="checked" {{$posts->count() > 0 ? '':'disabled'}}/>
							
							</th>
								<th>#</th>
								<th>Image</th>
								<th>Post Name</th>								
							</tr>
						</thead>
						<tbody>
							@foreach($posts as $key=>$post)
							<tr>
							<td><input type="checkbox"  name="id[]" 
								value="{{$post->id}}" class="check-all"></td>
								<td>{{++$key}}</td>
								<td>
									<img src="{{$post->post_featuredimg}}" class="img-responsive" width="100px" />
								</td>
								<td>{{$post->post_title}}</td>								
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
			</form>
		</div>
	</div>
</div>
@endsection

@include('backend.asset-partials.datatables')
@include('backend.asset-partials.form-function')