routes/web.php
<?php

use Illuminate\Support\Facades\Input;

/*******************************************************************************************
 *                                  AUTH
 *******************************************************************************************/

Auth::routes();

/*******************************************************************************************
 *                                  BACKEND
 *******************************************************************************************/

Route::group(['prefix' => 'backend', 'middleware' => 'backend', 'namespace' => 'Backend'], function () {
    // Dashboard
    Route::get('/', ['uses' => 'BackendsController@index', 'as' => 'backend.index']);

    // Posts
    Route::group(['prefix' => 'posts'], function () {
        Route::get('/trashed', ['uses' => 'PostsController@trashed', 'as' => 'posts.trashed']);
        Route::get('/shred/{id}', ['uses' => 'PostsController@shred', 'as' => 'posts.shred']);
        Route::delete('/massdelete', ['uses' => 'PostsController@massdelete', 'as' => 'posts.massdelete']);
        Route::get('/all', ['uses' => 'PostsController@allposts', 'as' => 'posts.all']);
    });

    Route::resource('posts', 'PostsController', ['except' => ['show', 'destroy']]);

    // Users
    Route::group(['prefix' => 'users'], function () {
        Route::get('/myaccount', ['uses' => 'UsersController@myaccount', 'as' => 'users.myaccount']);
        Route::post('/profile/update', ['uses' => 'ProfilesController@update', 'as' => 'profile.update']);
        Route::delete('/massdelete', ['uses' => 'UsersController@massdelete', 'as' => 'users.massdelete']);
    });
    Route::resource('users', 'UsersController');

    // Roles
    Route::group(['prefix' => 'roles'], function () {
        Route::delete('/massdelete', ['uses' => 'RolesController@massdelete', 'as' => 'roles.massdelete']);
    });
    Route::resource('roles', 'RolesController');

    // Permissions
    Route::group(['prefix' => 'permissions'], function () {
        Route::delete('/massdelete', ['uses' => 'PermissionsController@massdelete', 'as' => 'permissions.massdelete']);
    });
    Route::resource('permissions', 'PermissionsController');

    // Models
    Route::group(['prefix' => 'models'], function () {
        Route::delete('/massdelete', ['uses' => 'DatasetsController@massdelete', 'as' => 'models.massdelete']);

    });
    Route::resource('models', 'DatasetsController');

    // Menu Management Page
    Route::get('/menu', function () {
        $menu = DB::table('tbl_menus')->orderBy('order', 'ASC')->get();
        return view('backend.menus.menu', ['menus' => $menu]);
    });

    // Menu Manager
    Route::get('/managemenu', function () {
        $menu = DB::table('tbl_menus')->orderBy('order', 'ASC')->get();
        return view('backend.menus.menuManage', ['menus' => $menu]);
    });

    // Menu Sorter Function
    Route::get('/order-menu', function () {
        $menu = DB::table('tbl_menus')->orderBy('order', 'ASC')->get();
        $itemID = Input::get('itemID');
        $itemIndex = Input::get('itemIndex');

        foreach ($menu as $value) {
            return DB::table('tbl_menus')
                ->where('menu_id', '=', $itemID)
                ->update(array('order' => $itemIndex));
        }
        return redirect()->route('backend.index');
    });

    // Comments
    Route::group(['prefix' => 'comments'], function () {
        Route::delete('/massdelete', ['uses' => 'CommentsController@massdelete', 'as' => 'comments.massdelete']);
    });
    Route::resource('comments', 'CommentsController', ['except' => ['show', 'store', 'destroy']]);

    // Email

    Route::post('/send/email', ['uses'=> 'EmailController@send', 'as'=> 'emails.send']);
});

Route::get('/', ['uses' => 'HomeController@index']);

app/Models/Backend/Comment.php
<?php

namespace App\Models\Backend;
use App\Models\Backend\Post;
use App\Models\Backend\Category;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $guarded = [];
    
    public function post()
    {
        return $this->belongsTo(Post::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    
    public function category(){
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/Backend/BackendsController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

class BackendsController extends Controller
{
    public function index(){
        // return view('backend.dashboard');
        return redirect()->route('posts.all');
    }
}

app/Http/Controllers/Backend/CommentsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Backend\Comment;
use App\Models\Backend\Post;
use Illuminate\Http\Request;
use Session;
use App\Http\Requests\Backend\CommentsRequest;

class CommentsController extends Controller
{
    public function index(){
        return view('backend.comments.index')
        ->with('comments', Comment::all());
    }

    public function save(CommentsRequest $request,Post $post)
    {        
        $post->saveComment(
            request('description')
        );
        
        Session::flash('success', 'Your comment has been posted successfully');
        return redirect()->back();
    }

    public function edit($id){
        return view('backend.comments.edit')
        ->with('comment', Comment::find($id));        
    }

    public function update(CommentsRequest $request, $id){
        
        Comment::find($id)->update([
            'description' => $request->description,            
        ]);
        Session::flash('success', 'The comment was successfully updated');
        return redirect()->back();
    }

    public function massdelete(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Comment::find($id)->delete();
        }
        Session::flash('success', 'The comment(s) was successfully deleted');
        return redirect()->route('comments.index');
    }  
    
    public function kill(Post $post){
        $post->deleteComment(request('id'));
        Session::flash('success', 'The comment(s) was successfully deleted');
        return redirect()->route('comments.index');
    }
}

app/Http/Controllers/Backend/DatasetsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Backend\Dataset;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\DatasetsRequest;
use Illuminate\Http\Request;
use Session;

class DatasetsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.models.index')->with('datasets', Dataset::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.models.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DatasetsRequest $request)
    {
        Dataset::create([
            'name' => $request->name,
            'key' => str_slug($request->name),
            'description' => $request->description,
        ]);
        Session::flash('success', 'The model has been created');
        return redirect()->route('models.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('backend.models.edit')->with('dataset', Dataset::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DatasetsRequest $request, $id)
    {
        Dataset::find($id)->update([
            'name' => $request->name,
            'key' => str_slug($request->name),
            'description' => $request->description,
        ]);
        Session::flash('success', 'The model has been updated');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }

    public function massdelete(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Dataset::find($id)->delete();
        }
        Session::flash('success', 'The dataset(s) was successfully deleted');
        return redirect()->route('models.index');
    }
}

app/Http/Controllers/Backend/EmailController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EmailController extends Controller
{
    public function send(Request $request){
        
    }
}

app/Http/Controllers/Backend/PermissionsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Backend\Dataset;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\PermissionsRequest;
use App\Models\Permission;
use Illuminate\Http\Request;
use Session;

class PermissionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.permissions.index')->with('permissions', Permission::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.permissions.create')->with('models', Dataset::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PermissionsRequest $request)
    {
        Permission::create([
            'name' => ucwords($request->name),
            'slug' => str_slug($request->name),
            'description' => $request->description,
            'dataset_id' => $request->dataset_id
        ]);
        Session::flash('success', 'The permission was created successfully');
        return redirect()->route('permissions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('backend.permissions.edit')
        ->with('permission', Permission::find($id))
        ->with('models', Dataset::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PermissionsRequest $request, $id)
    {
        Permission::find($id)->update([
            'name' => ucwords($request->name),
            'slug' => str_slug($request->name),
            'description' => $request->description,
            'dataset_id' => $request->dataset_id
        ]);
        Session::flash('success', 'The permission has been updated successfully');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function massdelete(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Permission::find($id)->delete();
        }
        Session::flash('success', 'The permission(s) was successfully deleted');
        return redirect()->route('permissions.index');
    }
}

app/Http/Controllers/Backend/PostsController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\PostsRequest;
use DB;
use Auth;
use App\Models\Backend\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Session;
use Carbon\Carbon;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.posts.index')
        ->with('posts', Post::all());
    }

    public function allposts(){
        return view('backend.posts.all')
        ->with('posts', Post::all());
    }

    public function singlePost($post_slug){
        $post = Post::where('post_slug', $post_slug)->first();
        return view('backend.posts.single')->with('post', $post);
    }
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        return view('backend.posts.create');        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostsRequest $request)
    {
        
        $this->validate($request, [
            'post_featuredimg' => 'image',
        ]);
        // Start saving the image to /public/uploads/posts
        $featured = $request->file('post_featuredimg');
        $featured_new_name = time() . $featured->getClientOriginalName();
        $featured->move('uploads/post/', $featured_new_name);
        // Create new post
        $post = Post::create([
            'post_title' => $request->post_title,
            'post_slug' => str_slug($request->post_title),
            'post_content' => $request->post_content,
            'post_featuredimg' => '/uploads/post/' . $featured_new_name,
            'user_id' => Auth::id()
        ]);       

        // $post->post_categories()->attach($request->postcats);
        Session::flash('success', 'The post was succesfully saved');
        return redirect()->route('posts.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {               
        $post = Post::find($id);        
        return view('backend.posts.edit')
            ->with('post', $post);            
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostsRequest $request, $id)
    {
            $post = Post::find($id);
            $post->post_title = $request->post_title;
            $post->post_slug = str_slug($request->post_title);
            $post->post_content = $request->post_content;            
        
        if ($request->hasFile('post_featuredimg')) {
            $this->validate($request, [
                'featured' => 'image',
            ]);
            $featured = $request->file('post_featuredimg');
            $featured_new_name = time() . $featured->getClientOriginalName();
            $featured->move('uploads/posts', $featured_new_name);
            $post->post_featuredimg = '/uploads/posts/'.$featured_new_name;            
        }
            $post->save();
        Session::flash('success', 'The post was successfully update');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function massdelete(Request $request)
    {   
        $checked = $request->input('id', []);
        foreach($checked as $id){
            Post::find($id)->delete();
        }        
        Session::flash('success', 'The post was successfully deleted');
        return redirect()->route('posts.index');
    }  

    

    /**
     * Display a listing of the trashed posts.
     *
     * @return \Illuminate\Http\Response
     */

    public function trashed()
    {
        $posts = Post::onlyTrashed()->get();
        return view('backend.posts.trashed')->with('posts', $posts);

    }

    public function shred(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Post::onlyTrashed()->where('id', $id)->forceDelete();
        }
        Session::flash('success', 'The post was successfully deleted');
        return redirect()->route('posts.trashed');

    }

    public function bulkdelete(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Post::where('id', $id)->delete();
        }
        Session::flash('success', 'The post was successfully deleted');
        return redirect()->back();

    }

    public function restore(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Post::onlyTrashed()->where('id', $id)->restore();
        }
        Session::flash('success', 'The post was successfully restored');
        return redirect()->back();

    }
}

resources/views/backend/users/create.blade.php
@extends('backend.master') @section('content')
<div class="row">
  <div class="col-sm-12">
    <div class="element-wrapper">
      <h6 class="element-header">
        Add New User
      </h6>
      <div class="element-box">
        <form action="{{route('users.store')}}" method="post" enctype="multipart/form-data">
          {{csrf_field()}} 
          @include('backend.users.form')
          <div class="form-group">
            <button class="btn btn-primary" type="submit">
              Save
            </button>
            <a href="{{route('users.index')}}" class="btn btn-info">Back</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@stop

resources/views/backend/users/edit.blade.php
@extends('backend.master') @section('content')
<div class="row">
  <div class="col-sm-12">
    <div class="element-wrapper">
      <h6 class="element-header">
        Add New User
      </h6>
      <div class="element-box">
        <form action="{{route('users.update', ['id'=> $user->id])}}" method="post" enctype="multipart/form-data">
          {{csrf_field()}} 
          {{method_field('PUT')}}
          @include('backend.users.form')
          <div class="form-group">
            <button class="btn btn-primary" type="submit">
              Save Changes
            </button>
            <a href="{{route('users.index')}}" class="btn btn-info">Back</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@stop

resources/views/backend/users/form.blade.php
<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
    <label for="name">
        Username
    </label>
    <input name="name" type="text" class="form-control" value="{{old('name',$user->name ?? null)}}">
    <span class="help-block text-danger">
        <strong>{{ $errors->first('name') }}</strong>
    </span>
</div>
<div class="form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
    <label for="first_name">
        First Name
    </label>
    <input name="first_name" type="text" class="form-control" value="{{old('first_name',$user->profile->first_name ?? null)}}">
    <span class="help-block text-danger">
        <strong>{{ $errors->first('first_name') }}</strong>
    </span>
</div>
<div class="form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
    <label for="last_name">
        Last Name
    </label>
    <input name="last_name" type="text" class="form-control" value="{{old('last_name',$user->profile->last_name ?? null)}}">
    <span class="help-block text-danger">
        <strong>{{ $errors->first('last_name') }}</strong>
    </span>
</div>
<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
    <label for="email">
        Email
    </label>
    <input name="email" type="email" class="form-control" value="{{old('email',$user->email ?? null)}}">
    <span class="help-block text-danger">
        <strong>{{ $errors->first('email') }}</strong>
    </span>
</div>
<div class="form-group{{ $errors->has('avatar') ? ' has-error' : '' }}">
    <label for="avatar">
        Avatar
    </label>
    @if(!empty($user->profile->avatar))
    <div style="margin-top:20px;margin-bottom:20px">
        <img src="{{asset($user->profile->avatar)}}" style="width:100px" alt="">
    </div>
    @endif
    <input name="avatar" type="file" class="form-control" value="{{old('avatar',$user->profile->avatar ?? null)}}">
    <div class="help-block form-text text-muted form-control-feedback">
        Leave this blank if you dont want to change your profile picture
    </div>
    <span class="help-block text-danger">
        <strong>{{ $errors->first('avatar') }}</strong>
    </span>
</div>
<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
    <label for="password">
        Password
    </label>
    <input name="password" type="password" class="form-control" value="">
    <div class="help-block form-text text-muted form-control-feedback">
        Leave this blank if you dont want to change your password
    </div>
    <span class="help-block text-danger">
        <strong>{{ $errors->first('password') }}</strong>
    </span>
</div>
<div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
    <label for="password">
        Password Confirmation
    </label>
    <input id="password_confirmation" name="password_confirmation" type="password" class="form-control" value="">
    <span class="help-block text-danger">
        <strong>{{ $errors->first('password') }}</strong>
    </span>
</div>
<div class="form-group{{ $errors->has('role') ? ' has-error' : '' }}">
    <label for="role">
        Role
    </label>
    <select id="role" name="roles[]" class="form-control">
        @foreach($roles as $role)
            @if(in_array($role->id, $role_ids))
                <option value="{{$role->id}}" selected>{{$role->name}}</option>
                @else
                <option value="{{$role->id}}">{{$role->name}}</option>
            @endif 
        @endforeach
    </select>
    <span class="help-block text-danger">
        <strong>{{ $errors->first('role') }}</strong>
    </span>
</div>

resources/views/backend/users/index.blade.php
@extends('backend.master') 
@section('content')
<div class="row">
	<div class="col-sm-12">
		<div class="element-wrapper">
			<h6 class="element-header">
				Users
			</h6>
			<form class="form" action="{{route('users.massdelete')}}" method="post">
			{{csrf_field()}}
			{{method_field('DELETE')}}
			<div class="element-box">
			<div class="element-box-content">
			<div class="btn-group">
				<a href="{{route('users.create')}}" class="btn btn-primary">Add New Post</a>
			</div>
			<div class="btn-group">
				<button  class="btn btn-danger" id="bulk-delete" type="submit" name="bulkdelete" value="bulkdelete"  onclick="return confirm('Are you sure you want to move the selected record(s) to trash?')"><i class="os-icon os-icon-ui-15"></i> Move To Trash</button>
			</div>
			</div>
			</div>
			<div class="element-box">

				<div class="table-responsive">
					<table id="datatable" class="table table-striped ">
						<thead>
							<tr>
								<th>
									<input type="checkbox" id="selectall" class="checked" {{$users->count() > 1 ? '':'disabled'}} /></th>
								<th>#</th>
								<th>Image</th>
								<th>Name</th>
                                <th>Permission</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							@foreach($users as $key=>$user)
							<tr>
								<td><input type="checkbox" name="id[]"
								value="{{$user->id}}" class="check-all"
								{{Auth::id() == $user->id ? 'disabled':''}} 								f
								></td>
								<td>{{++$key}}</td>
								<td>
									<img src="{{asset($user->profile['avatar'])}}" class="img-responsive" width="100px" />
								</td>
								<td>{{$user->name}}</td>
								<td></td>                                
								<td class="row-actions">
									<a href="{{route('users.edit',['id'=>$user->id])}}">
										<i class="os-icon os-icon-pencil-2"></i> Edit
									</a>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</form>
		</div>
	</div>
</div>
@endsection

@include('backend.asset-partials.datatables')
@include('backend.asset-partials.form-function')